/**
 * STANDARD_METRICS_KB — Knowledge Base registry for every metric in AEMR.
 *
 * Maps metric keys to human-readable KB entries used by <KBTooltip>.
 * Each entry contains: formula, source, cell reference, thresholds, law, note.
 *
 * Design: single source of truth for all metric documentation across UI.
 * Every KPI card, table header, chart legend, and badge MUST reference this registry.
 */

import type { KBEntryData } from './types.js';

// ── Base Metrics (accumulated from department rows) ────────────────

export const METRIC_KB: Record<string, KBEntryData> = {
  // ── Counts ──
  plan_count: {
    label: 'План (кол-во)',
    formula: 'COUNT(rows) — количество строк закупок в плане',
    source: 'CalcEngine → total.plan_count',
    cell: 'СВОД ТД-ПМ!D{dept_row}',
    thresholds: 'Информационный показатель, пороги не применяются',
    law: '44-ФЗ ст.16 — планирование закупок',
    unit: 'count',
    category: 'execution',
  },
  fact_count: {
    label: 'Факт (кол-во)',
    formula: 'COUNT(rows WHERE fact_date IS NOT EMPTY)',
    source: 'CalcEngine → total.fact_count (gate: FACT_DATE notEmpty)',
    cell: 'СВОД ТД-ПМ!E{dept_row}',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.94 — исполнение контракта',
    unit: 'count',
    category: 'execution',
  },
  competitive_count: {
    label: 'КП (кол-во)',
    formula: 'COUNT(rows WHERE method IN {ЭА, ЭК, ЭЗК})',
    source: 'CalcEngine → total.competitive_count',
    cell: 'СВОД ТД-ПМ!D{dept_row} (filtered)',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.24 — способы определения поставщиков',
    unit: 'count',
    category: 'method',
  },
  ep_count: {
    label: 'ЕП (кол-во)',
    formula: 'COUNT(rows WHERE method = "ЕП")',
    source: 'CalcEngine → total.ep_count',
    cell: 'СВОД ТД-ПМ!D{dept_row} (EP only)',
    thresholds: 'Доля ЕП >10% — повышенный контроль',
    law: '44-ФЗ ст.93 — закупка у единственного поставщика',
    unit: 'count',
    category: 'method',
  },
  comp_fact_count: {
    label: 'Факт КП (кол-во)',
    formula: 'COUNT(rows WHERE method IN {ЭА,ЭК,ЭЗК} AND fact_date NOT EMPTY)',
    source: 'CalcEngine → total.comp_fact_count',
    cell: 'СВОД ТД-ПМ!G{dept_row}',
    thresholds: 'Исполнение КП ≥90% зелёный, ≥70% жёлтый, <70% красный',
    law: '44-ФЗ ст.24 — конкурентные способы',
    unit: 'count',
    category: 'execution',
  },
  ep_fact_count: {
    label: 'Факт ЕП (кол-во)',
    formula: 'COUNT(rows WHERE method = "ЕП" AND fact_date NOT EMPTY)',
    source: 'CalcEngine → total.ep_fact_count',
    cell: 'СВОД ТД-ПМ!G{dept_row} (EP)',
    thresholds: 'Исполнение ЕП ≥90% зелёный, ≥70% жёлтый, <70% красный',
    law: '44-ФЗ ст.93',
    unit: 'count',
    category: 'execution',
  },

  // ── Plan sums (budget limits) ──
  plan_fb: {
    label: 'Лимит ФБ',
    formula: 'SUM(col_H) — федеральный бюджет, лимит на закупки',
    source: 'CalcEngine → total.plan_fb (column H)',
    cell: 'СВОД ТД-ПМ!H{dept_row}',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.72 — планирование бюджетных обязательств',
    unit: 'currency',
    category: 'budget',
  },
  plan_kb: {
    label: 'Лимит КБ',
    formula: 'SUM(col_I) — краевой бюджет, лимит на закупки',
    source: 'CalcEngine → total.plan_kb (column I)',
    cell: 'СВОД ТД-ПМ!I{dept_row}',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.72',
    unit: 'currency',
    category: 'budget',
  },
  plan_mb: {
    label: 'Лимит МБ',
    formula: 'SUM(col_J) — муниципальный бюджет, лимит на закупки',
    source: 'CalcEngine → total.plan_mb (column J)',
    cell: 'СВОД ТД-ПМ!J{dept_row}',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.72',
    unit: 'currency',
    category: 'budget',
  },
  plan_total: {
    label: 'Лимит ИТОГО',
    formula: 'SUM(col_K) или SUM(H+I+J) если K пуст — общий лимит',
    source: 'CalcEngine → total.plan_total (column K, fallback H+I+J)',
    cell: 'СВОД ТД-ПМ!K{dept_row}',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.72 — планирование закупок',
    unit: 'currency',
    category: 'budget',
  },

  // ── Fact sums (contract prices) ──
  fact_fb: {
    label: 'Факт ФБ',
    formula: 'SUM(col_V WHERE fact_date NOT EMPTY) — цена контрактов ФБ',
    source: 'CalcEngine → total.fact_fb (column V, gate: FACT_DATE)',
    cell: 'СВОД ТД-ПМ!V{dept_row}',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.34 — цена контракта',
    unit: 'currency',
    category: 'budget',
  },
  fact_kb: {
    label: 'Факт КБ',
    formula: 'SUM(col_W WHERE fact_date NOT EMPTY) — цена контрактов КБ',
    source: 'CalcEngine → total.fact_kb (column W, gate: FACT_DATE)',
    cell: 'СВОД ТД-ПМ!W{dept_row}',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.34',
    unit: 'currency',
    category: 'budget',
  },
  fact_mb: {
    label: 'Факт МБ',
    formula: 'SUM(col_X WHERE fact_date NOT EMPTY) — цена контрактов МБ',
    source: 'CalcEngine → total.fact_mb (column X, gate: FACT_DATE)',
    cell: 'СВОД ТД-ПМ!X{dept_row}',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.34',
    unit: 'currency',
    category: 'budget',
  },
  fact_total: {
    label: 'Факт ИТОГО',
    formula: 'SUM(col_Y WHERE fact_date NOT EMPTY) или SUM(V+W+X)',
    source: 'CalcEngine → total.fact_total (column Y, fallback V+W+X)',
    cell: 'СВОД ТД-ПМ!Y{dept_row}',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.34 — цена контракта',
    unit: 'currency',
    category: 'budget',
  },

  // ── Economy (savings) ──
  economy_fb: {
    label: 'Экономия ФБ',
    formula: 'SUM(col_Z WHERE fact_date NOT EMPTY AND AD="да")',
    source: 'CalcEngine → total.economy_fb (column Z, gates: FACT_DATE + AD)',
    cell: 'СВОД ТД-ПМ!Z{dept_row}',
    thresholds: '>25% от лимита — подозрительно, требует обоснования',
    law: '44-ФЗ ст.34 п.1.1 — обоснование экономии',
    note: 'Только при AD="да" (утверждённая экономия)',
    unit: 'currency',
    category: 'economy',
  },
  economy_kb: {
    label: 'Экономия КБ',
    formula: 'SUM(col_AA WHERE fact_date NOT EMPTY AND AD="да")',
    source: 'CalcEngine → total.economy_kb (column AA, gates: FACT_DATE + AD)',
    cell: 'СВОД ТД-ПМ!AA{dept_row}',
    thresholds: '>25% от лимита — подозрительно',
    law: '44-ФЗ ст.34 п.1.1',
    note: 'Только при AD="да"',
    unit: 'currency',
    category: 'economy',
  },
  economy_mb: {
    label: 'Экономия МБ',
    formula: 'SUM(col_AB WHERE fact_date NOT EMPTY AND AD="да")',
    source: 'CalcEngine → total.economy_mb (column AB, gates: FACT_DATE + AD)',
    cell: 'СВОД ТД-ПМ!AB{dept_row}',
    thresholds: '>25% от лимита — подозрительно',
    law: '44-ФЗ ст.34 п.1.1',
    note: 'Только при AD="да"',
    unit: 'currency',
    category: 'economy',
  },

  // ── Method-specific plan totals ──
  comp_plan_total: {
    label: 'Лимит КП ИТОГО',
    formula: 'SUM(col_K WHERE method IN {ЭА, ЭК, ЭЗК})',
    source: 'CalcEngine → total.comp_plan_total',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.24 — конкурентные способы',
    unit: 'currency',
    category: 'method',
  },
  ep_plan_total: {
    label: 'Лимит ЕП ИТОГО',
    formula: 'SUM(col_K WHERE method = "ЕП")',
    source: 'CalcEngine → total.ep_plan_total',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.93 — единственный поставщик',
    unit: 'currency',
    category: 'method',
  },

  // ── Derived Metrics ──

  deviation: {
    label: 'Отклонение (кол-во)',
    formula: 'plan_count − fact_count',
    source: 'CalcEngine → derived.deviation',
    cell: 'СВОД ТД-ПМ!F{dept_row}',
    thresholds: '0 = выполнено, >0 = не завершены, <0 = перевыполнение',
    law: '44-ФЗ ст.16 — план-график',
    unit: 'count',
    category: 'execution',
  },
  amount_deviation: {
    label: 'Отклонение (сумма)',
    formula: 'plan_total − fact_total',
    source: 'CalcEngine → derived.amount_deviation',
    thresholds: '>0 = экономия/не освоено, <0 = перерасход',
    law: '44-ФЗ ст.34',
    unit: 'currency',
    category: 'execution',
  },
  execution_pct: {
    label: 'Исполнение (сумма)',
    unit: 'percent',
    category: 'execution',
    whatIs: 'Доля денег плана, которая освоена фактом. Финансовая тень count-метрики.',
    howCalc: 'SUM(fact_total) / SUM(plan_total) × 100. Бюджетный срез применяется: ФБ/КБ/МБ, если включён фильтр.',
    dataSource: 'СВОД ТД-ПМ · колонки plan_total/fact_total с разбивкой по бюджетам.',
    engine: 'departmentSummaries[*].quarters[q].{planTotal, factTotal}.',
    thresholdsFull: '🟢 ≥ 80 %\n🟡 50–79 %\n🔴 < 50 %\n🟣 > 100 % — факт > план (переосвоение)',
    lawFull: '44-ФЗ ст. 16, 94\nПланирование и исполнение в денежном выражении.',
    example: 'УКБ: план 2,1 млрд, факт 0,4 млрд → 19 % (🔴).',
    pitfalls: 'Без бюджетного фильтра это агрегат ФБ+КБ+МБ — включи срез «ФБ» для узкого взгляда.',
    actions: 'Секундарное значение основной карточки Исполнения. Клик → раскрытие.',
    related: ['exec_count_pct', 'economy_rate'],
    formula: 'SUM(fact_total) / SUM(plan_total)',
    source: 'CalcEngine.total.fact_total',
    cell: 'СВОД ТД-ПМ!H{dept_row}',
    thresholds: '≥80 / 50-80 / <50 / >100',
    law: '44-ФЗ ст.16, 94',
  },
  exec_count_pct: {
    label: 'Исполнение (количество)',
    unit: 'percent',
    category: 'execution',
    whatIs: 'Доля строк плана с закрытой датой факта. Главный показатель исполнения по закону: количество позиций, а не рубли.',
    howCalc: 'SUM(fact_count по всем ГРБС за период) / SUM(plan_count) × 100. Gate: fact_date NOT EMPTY.',
    dataSource: 'СВОД ТД-ПМ (ШДЮ fact для текущих цифр) · 558 строк × 41 колонка.',
    engine: 'CalcEngine.total.{plan_count, fact_count} → orchestrator → dashboardData.departmentSummaries[*].quarters[q].{planCount, factCount}.',
    thresholdsFull: '🟢 ≥ 80 % — в графике\n🟡 50–79 % — отстаёт\n🔴 < 50 % — срыв',
    lawFull: '44-ФЗ ст. 94\nИсполнение контракта — приёмка, оплата, закрытие позиции в реестре.',
    example: 'ЛК: план 120, факт 87 → 72,5 % (🟡).',
    pitfalls: 'Счёт строк, а не рублей — расхождение с «Исполнение (сумма)» нормально: дорогие позиции могут запаздывать.',
    actions: 'Кликни карточку → раскрытие по ГРБС · стрелка → Analytics с текущими фильтрами.',
    related: ['execution_pct', 'critical_issues'],
    formula: 'COUNT(fact_date!=∅) / COUNT(rows)',
    source: 'CalcEngine.total.fact_count',
    cell: 'СВОД ТД-ПМ!E{dept_row}',
    thresholds: '≥80% / 50-80% / <50%',
    law: '44-ФЗ ст.94',
    note: 'Основной KPI руководства: исполнение по количеству процедур',
  },
  comp_exec_count_pct: {
    label: '% исполнения КП (кол-во)',
    formula: 'comp_fact_count / competitive_count × 100',
    source: 'CalcEngine → derived.comp_exec_count_pct',
    cell: 'СВОД ТД-ПМ!G{dept_row} (КП)',
    thresholds: '≥90% зелёный, 70-89% синий, 50-69% жёлтый, <50% красный',
    law: '44-ФЗ ст.24 — конкурентные закупки',
    unit: 'percent',
    category: 'execution',
  },
  ep_exec_count_pct: {
    label: '% исполнения ЕП (кол-во)',
    formula: 'ep_fact_count / ep_count × 100',
    source: 'CalcEngine → derived.ep_exec_count_pct',
    thresholds: '≥90% зелёный, 70-89% синий, 50-69% жёлтый, <50% красный',
    law: '44-ФЗ ст.93 — единственный поставщик',
    unit: 'percent',
    category: 'execution',
  },
  savings_pct: {
    label: '% экономии',
    formula: '(plan_total − fact_total) / plan_total × 100',
    source: 'CalcEngine → derived.savings_pct',
    thresholds: '>25% подозрительно (требует AD-обоснования), 5-15% норма',
    law: '44-ФЗ ст.34 п.1.1 — обоснование НМЦК',
    unit: 'percent',
    category: 'economy',
  },
  economy_total: {
    label: 'Экономия ИТОГО',
    formula: 'economy_fb + economy_kb + economy_mb',
    source: 'CalcEngine → derived.economy_total',
    cell: 'СВОД ТД-ПМ!AC{dept_row}',
    thresholds: '>25% лимита → AD-контроль обязателен',
    law: '44-ФЗ ст.34 п.1.1',
    note: 'Только утверждённая экономия (AD="да")',
    unit: 'currency',
    category: 'economy',
  },
  total_procedures: {
    label: 'Всего процедур',
    formula: 'competitive_count + ep_count',
    source: 'CalcEngine → derived.total_procedures',
    thresholds: 'Информационный показатель',
    law: '44-ФЗ ст.24',
    unit: 'count',
    category: 'execution',
  },
  ep_share_pct: {
    label: 'Доля ЕП %',
    formula: 'ep_count / total_procedures × 100',
    source: 'CalcEngine → derived.ep_share_pct',
    thresholds: '>10% — повышенный контроль (рекомендация), >30% — критично',
    law: '44-ФЗ ст.93 — ограничение закупок у ЕП',
    note: 'Высокая доля ЕП = риск снижения конкуренции',
    unit: 'percent',
    category: 'method',
  },

  // ── Trust Components ──

  trust_overall: {
    label: 'Общая надёжность',
    formula: 'Σ(component_score × weight) → grade A-F',
    source: 'TrustScorer → overall',
    thresholds: 'A(≥90) зелёный, B(75-89) синий, C(60-74) жёлтый, D(40-59) оранжевый, F(<40) красный',
    law: 'Внутренний стандарт АЕМР — контроль достоверности данных',
    unit: 'percent',
    category: 'trust',
  },
  trust_data_quality: {
    label: 'Качество данных',
    formula: '100 − (missing_values_count + invalid_format_count) / total_cells × 100',
    source: 'TrustScorer → components[data_quality] (вес 30%)',
    thresholds: '≥90 хорошо, 70-89 внимание, <70 критично',
    unit: 'percent',
    category: 'trust',
  },
  trust_formula_integrity: {
    label: 'Целостность формул',
    formula: '100 − formula_errors / formula_cells × 100',
    source: 'TrustScorer → components[formula_integrity] (вес 25%)',
    thresholds: '≥95 хорошо, 85-94 внимание, <85 критично',
    unit: 'percent',
    category: 'trust',
  },
  trust_rule_compliance: {
    label: 'Соблюдение правил',
    formula: '100 − rule_violations / total_rules × 100',
    source: 'TrustScorer → components[rule_compliance] (вес 20%)',
    thresholds: '≥90 хорошо, 75-89 внимание, <75 критично',
    law: '44-ФЗ — правила ведения плана-графика',
    unit: 'percent',
    category: 'trust',
  },
  trust_mapping_consistency: {
    label: 'Согласованность маппинга',
    formula: '100 − mapping_mismatches / total_mappings × 100',
    source: 'TrustScorer → components[mapping_consistency] (вес 15%)',
    thresholds: '≥95 хорошо, 85-94 внимание, <85 критично',
    unit: 'percent',
    category: 'trust',
  },
  trust_operational_risk: {
    label: 'Операционный риск',
    formula: '100 − (overdue_count × 3 + economy_conflict_count × 2) / total_rows × 100',
    source: 'TrustScorer → components[operational_risk] (вес 10%)',
    thresholds: '≥85 хорошо, 70-84 внимание, <70 критично',
    unit: 'percent',
    category: 'trust',
  },

  // ── Dashboard-specific composite metrics ──

  critical_issues: {
    label: 'Критические замечания',
    unit: 'count',
    category: 'quality',
    whatIs: 'Сколько строк сейчас на «красном»: просрочка, факт без даты, переосвоение — всё, что требует действий сегодня.',
    howCalc: 'COUNT(issues WHERE severity IN {critical, error}). Считается из signals pipeline + ruleBook.',
    dataSource: 'packages/core/src/pipeline/signals.ts + shared/rule-book.ts.',
    engine: 'dashboardData.snapshot.issues фильтруется по severity.',
    thresholdsFull: '🟢 0 — чисто\n🟡 1–3 — контроль\n🔴 > 3 — сбор рабочей группы',
    lawFull: '44-ФЗ ст. 101\nКонтроль в сфере закупок — обязан выявлять и устранять нарушения.',
    example: '7 строк с «Факт > План» в УКС → критично.',
    pitfalls: 'Не путать с «Замечаниями» в RatingTable (сумма critical+warning).',
    actions: 'Клик карточки → раскрытие по ГРБС · стрелка → Quality > Issues с фильтром severity=critical.',
    related: ['signal_overdue', 'signal_fact_exceeds_plan'],
    formula: 'COUNT(severity IN {critical,error})',
    source: 'signals pipeline',
    cell: '—',
    thresholds: '0 / 1-3 / >3',
    law: '44-ФЗ ст.101',
  },
  economy_rate: {
    label: 'Экономия',
    unit: 'percent',
    category: 'economy',
    whatIs: 'Разница «план − факт» в процентах от плана. Зелёное до порога — хорошо; выше — флаг завышения НМЦК.',
    howCalc: '(plan_total − fact_total) / plan_total × 100.',
    dataSource: 'СВОД ТД-ПМ + ШДЮ fact.',
    engine: 'Derived on fd: economyTotal = totalPlan − totalFact.',
    thresholdsFull: '🟢 5–25 % — нормальная экономия\n🟡 < 5 % — слабая\n🟡 > 25 % — подозрение на завышение НМЦК\n🔴 < 0 — переосвоение',
    lawFull: '44-ФЗ ст. 22\nОбоснование НМЦК — завышенная экономия может указывать на нарушение.',
    example: 'План 1 млрд, факт 720 млн → 28 % (🟡: проверь НМЦК).',
    pitfalls: 'Положительная экономия не всегда благо — она может быть симптомом несделанного факта.',
    actions: 'Клик → раскрытие по ГРБС · стрелка → Economy.',
    related: ['execution_pct', 'signal_high_economy'],
    formula: '(plan − fact) / plan',
    source: 'CalcEngine',
    cell: 'derived',
    thresholds: '5-25% норма; >25% флаг',
    law: '44-ФЗ ст.22',
  },
  trust_binary: {
    label: 'Доверие к данным',
    unit: 'binary',
    category: 'trust',
    whatIs: 'Можно ли доверять цифрам на экране. Бинарный индикатор: норма или требуется проверка.',
    howCalc: 'Trust Score = 0,30·DataQuality + 0,25·FormulaIntegrity + 0,20·RuleCompliance + 0,15·MappingConsistency + 0,10·OperationalRisk. Бинаризация: ≥ 75 → норма.',
    dataSource: 'TrustEngine — анализ snapshot + rule-book + reconciliation.',
    engine: 'dashboardData.trust = {overall, dataQuality, formulaIntegrity, ...}.',
    thresholdsFull: '🟢 ≥ 75 — норма\n🔴 < 75 — проверь расхождения',
    lawFull: '44-ФЗ ст. 7\nПринцип открытости и прозрачности — данные должны быть достоверны.',
    example: 'Overall 82 → 🟢; кликни для разбивки по 5 компонентам.',
    pitfalls: 'Норма ≠ идеал — отдельные компоненты могут быть <60 и не всплыть.',
    actions: 'Клик → 5 компонентов с весами · стрелка → Quality > Trust.',
    related: ['trust_data_quality', 'trust_formula_integrity'],
    formula: 'weighted(5 components) → binary @75',
    source: 'TrustEngine',
    cell: 'derived',
    thresholds: '≥75 норма / <75 внимание',
    law: '44-ФЗ ст.7',
    note: 'Упрощённый индикатор для быстрого восприятия на Dashboard',
  },

  // ── RatingTable column metrics ──

  fb_execution_pct: {
    label: '% исполнения ФБ',
    formula: 'fact_fb / plan_fb × 100',
    source: 'CalcEngine → fact_fb / plan_fb',
    thresholds: '≥90% зелёный, 70-89% жёлтый, <70% красный',
    law: '44-ФЗ ст.72 — контроль ФБ (приоритет)',
    note: 'ФБ = федеральный бюджет, приоритет контроля',
    unit: 'percent',
    category: 'budget',
  },

  // ── Department-level RatingTable metrics ──
  // (merged from web/lib/metrics-registry.ts — единый реестр)

  dept_rank: {
    label: '№ (ранг в рейтинге)',
    unit: 'count',
    category: 'execution',
    whatIs: 'Порядковый номер управления в рейтинге по исполнению (количество). Чем выше позиция — тем лучше.',
    howCalc: 'Сортировка ГРБС по exec_count_pct убыванием. Топ-3 получают золотой/серебряный/бронзовый бейдж.',
    thresholdsFull: '🥇 1 место — лидер квартала\n🥈 2 место\n🥉 3 место\n• 4+ — базовая карточка',
    formula: 'rank() OVER (ORDER BY exec_count_pct DESC)',
    source: 'RatingTableV2 → sorted rows',
  },
  dept_name: {
    label: 'ГРБС — главный распорядитель',
    unit: 'count',
    category: 'execution',
    whatIs: 'Короткое наименование главного распорядителя бюджетных средств. При клике по строке — применяется фильтр по этому ГРБС.',
    howCalc: 'shortName из справочника департаментов (15 ГРБС). Полное имя — в подстроке. Подведы раскрываются по chevron.',
    thresholdsFull: '• Клик по строке → выделение (toggle)\n• Клик по chevron → раскрытие подведов\n• Клик по стрелке → переход к подробностям с сохранением фильтров',
    lawFull: 'Бюджетный кодекс РФ ст. 6, 158\nГРБС — орган власти, распоряжающийся средствами бюджета по ведомственной структуре.',
    formula: 'dept.nameShort',
    source: 'dashboardData.departmentSummaries[*].nameShort',
  },
  dept_exec_count_pct: {
    label: 'Исполнение по кол-ву (управление)',
    unit: 'percent',
    category: 'execution',
    whatIs: 'Доля закрытых строк плана у конкретного ГРБС. Главный индикатор «в графике / отстаёт / срыв».',
    howCalc: 'dept.factCount / dept.planCount × 100. Gate: fact_date NOT EMPTY. Учитывает подведы в составе ГРБС.',
    dataSource: 'СВОД ТД-ПМ + построчные листы подведов за выбранный период.',
    engine: 'CalcEngine.byDept[id].{plan_count, fact_count} → execution_pct. Срез period/month применяется до агрегата.',
    thresholdsFull: '🟢 ≥ 80 % — в графике\n🟡 50–79 % — отстаёт\n🔴 < 50 % — срыв',
    lawFull: '44-ФЗ ст. 94\nИсполнение контракта. Для ГРБС — сводный показатель по подведомственной сети.',
    example: 'УО: план 210, факт 168 → 80 % (🟢).',
    pitfalls: 'При выборе одного ГРБС строка раскрывается в подведы — их проценты считаются от их же плана, а не от плана ГРБС.',
    actions: 'Клик по строке → фильтр на ГРБС. Стрелка → deep-dive в DataBrowser.',
    related: ['dept_exec_amount_pct', 'exec_count_pct'],
    formula: 'dept.factCount / dept.planCount × 100',
    source: 'CalcEngine → byDept[id].exec_count_pct',
    thresholds: '≥90% зелёный, 70-89% синий, 50-69% жёлтый, <50% красный',
  },
  dept_exec_amount_pct: {
    label: 'Исполнение по сумме (управление)',
    unit: 'percent',
    category: 'execution',
    whatIs: 'Сколько денег плана освоено у ГРБС. Денежная тень count-метрики.',
    howCalc: 'dept.factTotal / dept.planTotal × 100. Учитывает бюджетный срез если включён.',
    dataSource: 'СВОД ТД-ПМ · plan_total/fact_total по подведам ГРБС.',
    engine: 'CalcEngine.byDept[id].{plan_total, fact_total} → execution_pct.',
    thresholdsFull: '🟢 ≥ 80 %\n🟡 50–79 %\n🔴 < 50 %\n🟣 > 100 % — переосвоение',
    lawFull: '44-ФЗ ст. 16, 94\nПланирование и исполнение в денежном выражении.',
    example: 'УКС: план 3,4 млрд, факт 2,7 млрд → 79 % (🟡).',
    pitfalls: 'Расхождение с «Исп. шт. %» нормально — крупные контракты могут запаздывать.',
    actions: 'Стрелка → детализация по квартал/месяц/бюджет.',
    related: ['dept_exec_count_pct', 'dept_fb_exec_pct'],
    formula: 'dept.factTotal / dept.planTotal × 100',
    source: 'CalcEngine → byDept[id].execution_pct',
    thresholds: '≥90% зелёный, 70-89% синий, 50-69% жёлтый, <50% красный',
  },
  dept_fb_exec_pct: {
    label: 'Исполнение ФБ (управление)',
    unit: 'percent',
    category: 'budget',
    whatIs: 'Процент освоения федерального бюджета у ГРБС. Приоритет контроля: ФБ — самые строгие требования.',
    howCalc: 'dept.factFB / dept.planFB × 100. Если plan_fb = 0 → «—» (ФБ не предусмотрен).',
    dataSource: 'СВОД ТД-ПМ · колонки H (план ФБ), V (факт ФБ).',
    engine: 'CalcEngine.byDept[id].fb_execution_pct.',
    thresholdsFull: '🟢 ≥ 80 % — в графике по ФБ\n🟡 50–79 % — риск возврата средств\n🔴 < 50 % — критично, возможен возврат',
    lawFull: 'БК РФ ст. 242 + 44-ФЗ ст. 72\nНеосвоение ФБ к концу года → возврат в федеральный бюджет. ГРБС несёт ответственность.',
    example: 'УАГЗО: план ФБ 420 млн, факт 310 млн → 74 % (🟡).',
    pitfalls: '«—» (прочерк) означает «ФБ не предусмотрен», а НЕ «0 %». Не красить в красный.',
    actions: 'Клик → разбивка по кварталам. Если < 50 % в конце года — эскалация финоргану.',
    related: ['dept_exec_amount_pct', 'fb_execution_pct'],
    formula: 'dept.factFB / dept.planFB × 100',
    source: 'CalcEngine → byDept[id].fb_execution_pct',
    cell: 'СВОД!столбцы H (план ФБ) / V (факт ФБ)',
    thresholds: '≥80% зелёный, 50-79% жёлтый, <50% красный',
    law: '44-ФЗ + БК РФ — федеральный бюджет = приоритет контроля',
  },
  dept_fb_pct: {
    label: 'Исполнение по ФБ (управление)',
    formula: 'dept.factFB / dept.planFB × 100',
    source: 'CalcEngine → byDept[id].fb_execution_pct',
    cell: 'СВОД!столбцы H (план ФБ) / L (факт ФБ)',
    thresholds: '≥90% зелёный, <50% красный',
    law: '44-ФЗ — федеральный бюджет = приоритет контроля',
    unit: 'percent',
    category: 'budget',
  },
  dept_trust: {
    label: 'Уровень доверия (управление)',
    unit: 'score',
    category: 'trust',
    whatIs: 'Можно ли доверять цифрам этого ГРБС. Сводный балл из 5 компонентов TrustEngine.',
    howCalc: 'TrustScorer(dept) = 0,30·DQ + 0,25·FI + 0,20·RC + 0,15·MC + 0,10·OR. Бинаризация: ≥ 75 → норма.',
    dataSource: 'TrustEngine по срезу dept: snapshot.issues + rule-book + reconciliation.',
    engine: 'TrustScorer → byDept[id].score → grade A–F.',
    thresholdsFull: '🟢 A (≥ 90) — эталон\n🟢 B (75–89) — норма\n🟡 C (60–74) — точечные проблемы\n🟠 D (40–59) — системные проблемы\n🔴 F (< 40) — данные под вопросом',
    lawFull: '44-ФЗ ст. 7\nПринцип открытости и прозрачности — данные должны быть достоверны.',
    example: 'УФБП: Trust 82 → B (🟢), но DQ = 58 — проверь качество заполнения.',
    pitfalls: 'Общий балл маскирует слабые компоненты. При < 75 — раскрыть по 5 метрикам.',
    actions: 'Клик → разбивка на 5 компонентов. Ниже 60 — эскалация финоргану.',
    related: ['trust_overall', 'trust_data_quality'],
    formula: 'TrustScorer(dept) → A/B/C/D/F',
    source: 'TrustScorer → byDept[id].score',
    thresholds: 'A(≥90) зелёный, B(75-89) синий, C(60-74) жёлтый, D(40-59) оранжевый, F(<40) красный',
  },
  dept_issues: {
    label: 'Количество замечаний (управление)',
    unit: 'count',
    category: 'quality',
    whatIs: 'Сколько замечаний по ГРБС: критические + предупреждения. Красный бейдж — critical, янтарный — warning.',
    howCalc: 'count(issues WHERE dept = id). Учитывает severity: critical + error + warning + significant.',
    dataSource: 'snapshot.issues (pipeline signals + rule-book) с группировкой по dept.',
    engine: 'Issues фильтруются по severity и группируются. Красный бейдж считает только critical + error.',
    thresholdsFull: '🟢 0 — чисто\n🟡 1–5 — точечный контроль\n🔴 > 5 — системные проблемы',
    lawFull: '44-ФЗ ст. 101\nКонтроль в сфере закупок. Каждое замечание — потенциальное нарушение.',
    example: 'УКС: 3 critical + 4 warning → бейдж «3 / 4».',
    pitfalls: 'Не путать с «Критические замечания» Hero KPI (только critical+error). Здесь — общий счёт.',
    actions: 'Клик → список замечаний ГРБС. Стрелка → Quality > Issues с фильтром.',
    related: ['critical_issues', 'signal_overdue'],
    formula: 'count(issues WHERE dept = id)',
    source: 'snapshot.issues → group by dept',
  },
  dept_delta_week: {
    label: 'Δ нед (изменение за неделю)',
    unit: 'percent',
    category: 'execution',
    whatIs: 'Насколько изменился процент исполнения ГРБС за последние 7 дней. Тренд: идёт ли динамика в нужную сторону.',
    howCalc: '(exec_count_pct_today − exec_count_pct_week_ago) pp. Источник — weekly snapshot.',
    dataSource: 'dashboardData.snapshot.deltas.byDept[id].execPctChange.',
    engine: 'useMultiDimMetrics hook читает delta из снапшотов; если снапшот отсутствует → «—».',
    thresholdsFull: '🟢 Δ > +1 pp — рост\n• Δ ±1 pp — стабильно\n🔴 Δ < −1 pp — падение',
    lawFull: '44-ФЗ ст. 72\nКонтроль за своевременностью исполнения — недельная динамика важна в финале квартала.',
    example: 'УО: 78 % → 81 % за неделю → Δ +3,0 pp (🟢).',
    pitfalls: 'Без недельного снапшота Δ скрыт — это норма, не ошибка. Не красить «—» в красный.',
    actions: 'Падение > 1 pp две недели подряд — эскалация, возможны срывы контрактов.',
    related: ['dept_exec_count_pct', 'dept_sparkline'],
    formula: 'pct_today − pct_week_ago',
    source: 'dashboardData.snapshot.deltas',
    thresholds: '> +1pp рост / ±1pp стабильно / < −1pp падение',
  },
  dept_sparkline: {
    label: 'Спарк (4 квартала)',
    unit: 'percent',
    category: 'execution',
    whatIs: 'Мини-график динамики исполнения ГРБС по кварталам Q1→Q4. 4 точки — чтобы глаз зацепился за тренд.',
    howCalc: 'Массив exec_count_pct за 4 квартала текущего года. Последняя точка — жирная.',
    dataSource: 'dashboardData.departmentSummaries[*].quarters[q1..q4].',
    engine: 'recharts AreaChart 56×20 px, currentColor, last-point dot.',
    thresholdsFull: '📈 Восходящий тренд — ГРБС набирает темп\n📉 Нисходящий — риск срыва\n〰️ Плоский — застой, нужна активизация',
    lawFull: '44-ФЗ ст. 16\nПлан-график закупок распределяется по кварталам — динамика показывает соответствие плану.',
    example: 'УЭР: 45 → 62 → 71 → 79 → восходящий тренд, к концу года цель.',
    pitfalls: 'Низкая база в Q1 — норма для долгих контрактов. Всплески в Q4 — типичный «декабрьский рывок».',
    actions: 'Наведи на точку — увидишь % и квартал. Плоская линия → проверь активность закупок.',
    related: ['dept_exec_count_pct', 'dept_delta_week'],
    formula: '[exec_count_pct(q1..q4)]',
    source: 'CalcEngine.byDept[id].quarters',
  },

  // ── Economy (extended) ──

  total_economy: {
    label: 'Общая экономия (сумма)',
    formula: 'Σ(plan_limit − fact_price) WHERE fact > 0',
    source: 'CalcEngine → totals.economy_total',
    cell: 'СВОД ТД-ПМ!Z-AC (агрегат по управлениям)',
    law: '44-ФЗ ст.34 п.1 — цена контракта',
    unit: 'currency',
    category: 'economy',
    // ── 10-блочный KB (литературный русский) ──
    whatIs: 'Общая экономия бюджетных средств по всем завершённым закупкам, где финансовый орган подтвердил наличие экономии.',
    howCalc: 'Рассчитывается как сумма разниц между лимитом на закупку в рамках объёмов средств, предусмотренных муниципальной программой на год, и фактической ценой заключённого контракта. В расчёт входят только те закупки, где финансовый орган установил флаг экономии в столбце AD = «да». Экономия учитывается отдельно по трём видам бюджета: федеральному (ФБ), краевому (КБ) и муниципальному (МБ), затем суммируется.',
    dataSource: 'Исходные данные: таблица «СВОД для Google», лист «СВОД ТД-ПМ». Столбцы: Z (экономия ФБ), AA (экономия КБ), AB (экономия МБ), AC (экономия ИТОГО). Построчные данные: листы каждого управления (УЭР, УИО, УАГЗО, УФБП, УД, УДТХ, УКСиМП, УО).',
    engine: 'Расчётный движок программы (CalcEngine) проходит каждую строку закупки из листов управлений, отбирает строки с флагом AD=«да» и заполненной датой факта, суммирует экономию ФБ+КБ+МБ, и группирует результат по кварталам, управлениям, подведомственным организациям и видам бюджета. Итоговое значение сверяется с официальным из СВОД.',
    thresholdsFull: '🟢 5–15% от лимита программы — нормальная экономия на торгах\n🟡 < 2% — подозрение на предрешённость (возможный сговор, формальные торги)\n🔴 > 25% — высокая экономия, требует проверки обоснования НМЦК',
    lawFull: 'Статья 34, часть 1, 44-ФЗ «О контрактной системе»\nКонтракт заключается на условиях, предусмотренных извещением, по цене, предложенной победителем. Экономия возникает как разница между лимитом мероприятия муниципальной программы и фактической ценой контракта. НЕ путать с НМЦК — начальная максимальная цена одной закупки (определяется по ст.22) и лимит программы — это РАЗНЫЕ величины.',
    example: 'УЭР: лимит программы 12 400 тыс. руб., цена контракта 10 108 тыс. руб. Экономия: 2 292 тыс. руб. (18.5%). Флаг AD = «да» → входит в расчёт. Разбивка: ФБ 0, КБ 1 840, МБ 452 тыс. руб.',
    pitfalls: 'Экономия считается от лимита на закупку в рамках муниципальной программы, а НЕ от НМЦК и НЕ от средней рыночной цены. Лимит — объём средств, предусмотренный на мероприятие программы. НМЦК — начальная максимальная цена одной конкретной закупки (определяется отдельно по ст.22). Если флаг AD не установлен финансовым органом — закупка НЕ входит в расчёт. Отрицательная экономия (факт > лимита) — сигнал «economyConflict».',
    actions: 'Если > 25%: запросить у ГРБС обоснование НМЦК и проверить применение антидемпинговых мер (ст. 37, 44-ФЗ). Если < 2%: проверить наличие конкурентных заявок, проанализировать состав участников торгов. Если флаг AD не установлен: направить запрос финансовому органу.',
    related: ['economy_rate', 'economy_fb', 'economy_kb', 'economy_mb', 'high_economy_count', 'economy_conflicts', 'savings_pct'],
  },
  avg_reduction_pct: {
    label: 'Средний % снижения от лимита',
    formula: 'avg((limit − price) / limit × 100)',
    source: 'CalcEngine → totals.avg_reduction',
    thresholds: '0-10% нормально, >25% подозрительно',
    unit: 'percent',
    category: 'economy',
    // ── 10-блочный KB ──
    whatIs: 'Средний процент экономии бюджетных средств по всем управлениям — показывает, насколько эффективно проходят торги в целом по муниципалитету.',
    howCalc: 'Для каждого управления (ГРБС) рассчитывается процент экономии: (лимит программы − факт контракта) / лимит программы × 100. Затем берётся среднее арифметическое по всем управлениям. Учитываются только закупки с установленным флагом AD и заполненной датой факта.',
    dataSource: 'Рассчитывается из данных листа «СВОД ТД-ПМ»: столбцы H-K (лимиты), V-Y (факт), Z-AC (экономия). Построчно — из листов 8 управлений.',
    engine: 'CalcEngine рассчитывает % экономии для каждого dept из byDept[id], затем усредняет. Фильтрация по кварталу, месяцу, бюджету применяется ДО расчёта среднего.',
    thresholdsFull: '🟢 5–15% — нормальная конкурентная экономия\n🟡 < 2% — слишком низкая, подозрение на формальные торги или сговор\n🔴 > 25% — слишком высокая, риск заниженной НМЦК или демпинга',
    lawFull: 'Статья 37, 44-ФЗ — Антидемпинговые меры\nПри снижении цены на 25% и более от НМЦК при НМЦК ≤ 15 млн руб., участник обязан предоставить обеспечение исполнения контракта в 1.5-кратном размере. Это защита от недобросовестного демпинга.',
    example: 'При 8 управлениях с экономией: 12%, 8%, 15%, 3%, 22%, 7%, 11%, 9%. Среднее = (12+8+15+3+22+7+11+9)/8 = 10.9%. Это в зелёной зоне.',
    pitfalls: 'Среднее может маскировать крайности: если одно управление — 1%, а другое — 30%, среднее будет ~15% (зелёное). Поэтому всегда смотрите таблицу по управлениям в деталях. Также: пустые управления (нет закупок с фактом) не входят в расчёт.',
    actions: 'Если среднее > 25%: системная проблема с обоснованием НМЦК — провести аудит. Если < 2%: проверить конкуренцию в торгах, долю ЕП. Если разброс большой (от 1% до 30%): разобраться по каждому управлению отдельно.',
    related: ['total_economy', 'high_economy_count', 'savings_pct', 'economy_rate'],
  },
  high_economy_count: {
    label: 'Закупки с экономией > 25%',
    formula: 'count(rows WHERE (limit − price) / limit > 0.25)',
    source: 'signals.highEconomy count',
    thresholds: '0 зелёный, >5 жёлтый, >10 красный',
    law: '44-ФЗ ст.37 — антидемпинговые меры',
    unit: 'count',
    category: 'economy',
    // ── 10-блочный KB ──
    whatIs: 'Количество закупок, где экономия превысила 25% от лимита программы — маркер потенциального демпинга или завышения НМЦК.',
    howCalc: 'Подсчитывается количество строк закупок, где (лимит программы − цена контракта) / лимит программы > 0.25. То есть фактическая цена составила менее 75% от запланированного лимита. Считается построчно по каждой закупке, не по агрегатам.',
    dataSource: 'Строки из листов 8 управлений. Лимит: столбец K (итого). Факт: столбец Y (итого). Сигнал highEconomy генерируется движком сигналов при расчёте.',
    engine: 'Модуль сигналов (signals.ts) при обработке каждой строки проверяет условие: если factTotal > 0 И (planTotal − factTotal) / planTotal > 0.25, то генерирует сигнал highEconomy. Счётчик суммируется по управлениям.',
    thresholdsFull: '🟢 0 закупок — норма, экономия в пределах ожидаемого\n🟡 1–5 закупок — требуют точечной проверки обоснований\n🔴 > 5 закупок — системная проблема, возможно завышение НМЦК',
    lawFull: 'Статья 37, 44-ФЗ — Антидемпинговые меры при проведении конкурса и аукциона\nПри снижении цены контракта на 25% и более от НМЦК (при НМЦК ≤ 15 млн руб.) участник обязан предоставить обеспечение исполнения контракта в полуторакратном размере. При НМЦК > 15 млн руб. — обеспечение в полуторакратном размере ИЛИ информация о 3 ранее исполненных контрактах без штрафов.',
    example: 'УДТХ: 3 закупки на ремонт дорог с экономией 32%, 28%, 41%. Все три попадают в счётчик. Итого: high_economy_count = 3 для УДТХ. Необходимо запросить обоснование НМЦК и проверить исполнение контрактов.',
    pitfalls: 'Высокая экономия не всегда означает нарушение. Причины: завышенная НМЦК (ошибка расчёта по ст.22), сильная конкуренция, сезонное снижение цен, оптовые скидки. Но каждый случай требует проверки. Также: этот показатель считает от лимита программы, а ст.37 оперирует снижением от НМЦК — это разные базы.',
    actions: 'Для каждой закупки с экономией > 25%: (1) запросить обоснование НМЦК по ст.22, (2) проверить применение антидемпинга по ст.37, (3) проверить исполнение контракта (нет ли расторжения). Если массово: инициировать аудит методики расчёта НМЦК в управлении.',
    related: ['total_economy', 'avg_reduction_pct', 'signal_high_economy', 'economy_conflicts'],
  },
  economy_conflicts: {
    label: 'Конфликты флага экономии',
    formula: 'count(rows WHERE economyConflict signal)',
    source: 'signals.economyConflict count',
    thresholds: '0 зелёный, >0 красный',
    note: 'Финансовый орган не определил флаг AD при экономии >15%',
    unit: 'count',
    category: 'economy',
    // ── 10-блочный KB ──
    whatIs: 'Количество закупок, где наблюдается противоречие: расчётная экономия существует, но финансовый орган не установил флаг AD, или наоборот — флаг установлен при отсутствии экономии.',
    howCalc: 'Подсчитываются строки закупок, где выполняется одно из условий: (1) расчётная экономия > 15% от лимита, но AD ≠ «да» — финорган не подтвердил очевидную экономию; (2) AD = «да», но расчётная экономия ≤ 0 — флаг установлен ошибочно.',
    dataSource: 'Столбец AD (флаг экономии) из листов управлений. Расчётная экономия: столбцы Z-AC из СВОД ТД-ПМ. Проверка выполняется построчно.',
    engine: 'Модуль сигналов (signals.ts) при обработке строки сравнивает значение AD с расчётной экономией. Если они противоречат друг другу, генерируется сигнал economyConflict. Счётчик группируется по управлениям.',
    thresholdsFull: '🟢 0 конфликтов — все флаги согласованы\n🔴 > 0 конфликтов — требуется вмешательство финансового органа',
    lawFull: 'Статья 34, часть 1, 44-ФЗ\nЗаказчик обязан заключить контракт по цене, определённой торгами. Экономия — разница между лимитом программы и фактической ценой. Флаг AD — внутренний учётный механизм финансового органа для подтверждения экономии. Не регламентирован 44-ФЗ напрямую, но необходим для корректного учёта бюджетных средств.',
    example: 'УО: лимит 5 000 тыс. руб., факт 3 200 тыс. руб., экономия 36%. Но AD = «нет». Это конфликт: очевидная экономия не подтверждена финорганом. Возможно, флаг забыли установить, или экономия оспаривается.',
    pitfalls: 'Конфликт ≠ ошибка. Финорган может сознательно не ставить флаг, если: (1) экономия ещё не подтверждена актами, (2) контракт не исполнен до конца, (3) планируется дополнительное соглашение. Но каждый конфликт нужно разобрать.',
    actions: 'При наличии конфликтов: направить запрос финансовому органу с перечнем строк. Для каждой строки: уточнить причину расхождения, установить или обосновать отсутствие флага AD. Массовые конфликты (> 10) в одном управлении — сигнал о системной проблеме учёта.',
    related: ['total_economy', 'signal_economy_conflict', 'high_economy_count', 'economy_rate'],
  },

  // ── Chart/Dashboard metrics ──

  plan_fact_quarterly: {
    label: 'План/Факт по кварталам',
    formula: 'КП_plan + ЕП_plan (stacked) vs fact line',
    source: 'CalcEngine → summaryByPeriod[q1..q4]',
    cell: 'СВОД!G строки кварталов',
    unit: 'count',
    category: 'execution',
  },
  execution_by_dept: {
    label: 'Исполнение по управлениям (bar chart)',
    formula: 'dept.factTotal / dept.planTotal × 100 (bar) + exec_count_pct (line)',
    source: 'CalcEngine → barData',
    unit: 'percent',
    category: 'execution',
  },
  pie_procurement: {
    label: 'Распределение по способу закупки',
    formula: 'count КП vs count ЕП',
    source: 'CalcEngine → totalKP, totalEP',
    unit: 'count',
    category: 'method',
  },
  pie_budget: {
    label: 'Распределение по бюджетам',
    formula: 'planFB + planKB + planMB',
    source: 'CalcEngine → depts[].quarters[].planFB/KB/MB',
    law: '44-ФЗ — бюджетная классификация',
    unit: 'currency',
    category: 'budget',
  },

  // ── Signal metrics (for signal grid & quality page) ──

  signal_overdue: {
    label: 'Просрочка',
    formula: 'planDate < today AND factDate = null AND factSum = 0',
    source: 'signals.overdue',
    thresholds: '0 зелёный, >0 красный',
    law: '44-ФЗ ст.21 — план-график',
    unit: 'count',
    category: 'quality',
  },
  signal_economy_conflict: {
    label: 'Экономия без флага AD',
    formula: 'limit > price >15% AND AD ≠ "да"',
    source: 'signals.economyConflict',
    law: '44-ФЗ — учёт экономии',
    unit: 'count',
    category: 'economy',
  },
  signal_high_economy: {
    label: 'Снижение от лимита > 25%',
    formula: '(limit − price) / limit > 0.25',
    source: 'signals.highEconomy',
    thresholds: '>25% подозрительно',
    law: '44-ФЗ ст.37 — антидемпинг',
    unit: 'count',
    category: 'economy',
  },
  signal_stalled_contract: {
    label: 'Подвисший контракт',
    formula: 'signedDate < today − 30d AND factSum = 0',
    source: 'signals.stalledContract',
    unit: 'count',
    category: 'quality',
  },
  signal_fact_exceeds_plan: {
    label: 'Факт превышает план',
    formula: 'factSum > planSum (при planSum > 0)',
    source: 'signals.factExceedsPlan',
    thresholds: '>0% срабатывание, >10% критично',
    unit: 'count',
    category: 'quality',
  },
  signal_fact_date_before_plan: {
    label: 'Дата факта раньше даты плана',
    formula: 'factDate < planDate (разница 1-30 дней)',
    source: 'signals.factDateBeforePlan',
    unit: 'count',
    category: 'quality',
  },
  signal_plan_without_execution: {
    label: 'План без исполнения',
    formula: 'planSum > 0 AND planDate set AND factSum = 0 AND month ≥ April',
    source: 'signals.planWithoutExecution',
    law: '44-ФЗ ст.72 — своевременность',
    unit: 'count',
    category: 'quality',
  },
  signal_ep_justification_missing: {
    label: 'ЕП без обоснования',
    formula: 'method = ЕП AND justification (col M) = empty',
    source: 'signals.epJustificationMissing',
    law: '44-ФЗ ст.93 — обоснование ЕП',
    unit: 'count',
    category: 'quality',
  },
  signal_budget_underallocation: {
    label: 'Факт без плана',
    formula: 'factSum > 0 AND planSum = 0',
    source: 'signals.budgetUnderallocation',
    note: 'Бюджетная аномалия — расходы без плановых ассигнований',
    unit: 'count',
    category: 'quality',
  },
};

// ── Helpers ──

/** Get KB entry for a metric key. Returns undefined if not found. */
export function getMetricKB(key: string): KBEntryData | undefined {
  return METRIC_KB[key];
}

/** Get KB entry formatted for KBTooltip component. */
export function getMetricTooltip(key: string): {
  formula?: string;
  source?: string;
  cell?: string;
  thresholds?: string;
  law?: string;
  note?: string;
} | undefined {
  const entry = METRIC_KB[key];
  if (!entry) return undefined;
  return {
    formula: entry.formula,
    source: entry.source,
    cell: entry.cell,
    thresholds: entry.thresholds,
    law: entry.law,
    note: entry.note,
  };
}

/** Get all metrics in a category. */
export function getMetricsByCategory(category: KBEntryData['category']): Array<{ key: string } & KBEntryData> {
  return Object.entries(METRIC_KB)
    .filter(([, v]) => v.category === category)
    .map(([key, v]) => ({ key, ...v }));
}

/** List of all available metric keys. */
export const ALL_METRIC_KEYS = Object.keys(METRIC_KB);
